# Generated by Django 4.2.7 on 2026-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_tienda',
            field=models.CharField(blank=True, help_text='Nombre personalizado para tu página/tienda. Si está vacío, se usará tu nombre de usuario.', max_length=200, null=True),
        ),
    ]
