# Generated by Django 4.2.7 on 2026-01-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_question_offer_message_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor Logístico',
                'verbose_name_plural': 'Proveedores Logísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cotizado', 'Cotizado'), ('Creado', 'Creado'), ('Despachado', 'Despachado'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Error', 'Error')], default='Pendiente', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('etiqueta_url', models.URLField(blank=True, null=True)),
                ('dias_estimados', models.IntegerField(blank=True, null=True)),
                ('proveedor_envio_id', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='api.order')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='largo_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='api.shipment')),
            ],
            options={
                'verbose_name': 'Evento de Tracking',
                'verbose_name_plural': 'Eventos de Tracking',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
