# Generated by Django 4.2.7 on 2026-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carrier_shipment_product_alto_cm_product_ancho_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de cabecera para tu página pública.', null=True, upload_to='banners/'),
        ),
    ]
